import { ISeatSchemaOutput, SeatType } from './types'

const seatsSchemaInput1 = {
  colLength: 4,
  rowLength: 3,
  positionsExclude: [
    {
      row: 1,
      col: 1,
    },
    {
      row: 1,
      col: 4,
    },
    {
      row: 3,
      col: 1,
    },
    {
      row: 3,
      col: 4,
    },
  ],
  areasExclude: [
    {
      colStart: 2,
      colEnd: 3,
      rowStart: 2,
      rowEnd: 2,
    },
  ],
}
const seatsSchemaInput2 = {
  colLength: 4,
  rowLength: 4,
  positionsExclude: [
    {
      row: 1,
      col: 1,
    },
    {
      row: 2,
      col: 1,
    },
    {
      row: 1,
      col: 4,
    },
    {
      row: 4,
      col: 1,
    },
  ],
  areasExclude: [
    {
      colStart: 2,
      colEnd: 4,
      rowStart: 2,
      rowEnd: 3,
    },
  ],
}
const seatsSchemaInput3 = {
  colLength: 6,
  rowLength: 9,
  positionsExclude: [
    {
      col: 4,
      row: 1,
    },
    {
      col: 1,
      row: 4,
    },
    {
      col: 1,
      row: 2,
    },
    {
      col: 3,
      row: 2,
    },
    {
      col: 5,
      row: 2,
    },
    {
      col: 6,
      row: 2,
    },
    {
      col: 6,
      row: 4,
    },
    {
      col: 6,
      row: 5,
    },
    {
      col: 1,
      row: 6,
    },
    {
      col: 3,
      row: 9,
    },
    {
      col: 4,
      row: 9,
    },
  ],
  areasExclude: [
    {
      colStart: 1,
      colEnd: 2,
      rowStart: 1,
      rowEnd: 1,
    },
    {
      colStart: 2,
      colEnd: 5,
      rowStart: 3,
      rowEnd: 4,
    },
    {
      colStart: 3,
      colEnd: 5,
      rowStart: 5,
      rowEnd: 6,
    },
    {
      colStart: 1,
      colEnd: 6,
      rowStart: 7,
      rowEnd: 8,
    },
  ],
}

/**
 * Cut output schemas (after seat schema generating)
 */

const seatsSchemaOutput1 = [
  { col: 1, row: 2 },
  { col: 2, row: 1 },
  { col: 2, row: 3 },
  { col: 3, row: 1 },
  { col: 3, row: 3 },
  { col: 4, row: 2 },
]
const seatsSchemaOutput2 = [
  { col: 1, row: 3 },
  { col: 2, row: 1 },
  { col: 2, row: 4 },
  { col: 3, row: 1 },
  { col: 3, row: 4 },
  { col: 4, row: 4 },
]
const seatsSchemaOutput3 = [
  { col: 1, row: 3 },
  { col: 1, row: 5 },
  { col: 1, row: 9 },
  { col: 2, row: 2 },
  { col: 2, row: 5 },
  { col: 2, row: 6 },
  { col: 2, row: 9 },
  { col: 3, row: 1 },
  { col: 4, row: 2 },
  { col: 5, row: 1 },
  { col: 5, row: 9 },
  { col: 6, row: 1 },
  { col: 6, row: 3 },
  { col: 6, row: 6 },
  { col: 6, row: 9 },
]

/**
 * Full output schemas (after recovery)
 */
const seatsSchemaOutputFull1: ISeatSchemaOutput = [
  { col: 1, row: 1, type: SeatType.EMPTY },
  { col: 1, row: 2, type: SeatType.SEAT },
  { col: 1, row: 3, type: SeatType.EMPTY },
  { col: 2, row: 1, type: SeatType.SEAT },
  { col: 2, row: 2, type: SeatType.EMPTY },
  { col: 2, row: 3, type: SeatType.SEAT },
  { col: 3, row: 1, type: SeatType.SEAT },
  { col: 3, row: 2, type: SeatType.EMPTY },
  { col: 3, row: 3, type: SeatType.SEAT },
  { col: 4, row: 1, type: SeatType.EMPTY },
  { col: 4, row: 2, type: SeatType.SEAT },
  { col: 4, row: 3, type: SeatType.EMPTY },
]
const seatsSchemaOutputFull2: ISeatSchemaOutput = [
  { col: 1, row: 1, type: SeatType.EMPTY },
  { col: 1, row: 2, type: SeatType.EMPTY },
  { col: 1, row: 3, type: SeatType.SEAT },
  { col: 1, row: 4, type: SeatType.EMPTY },
  { col: 2, row: 1, type: SeatType.SEAT },
  { col: 2, row: 2, type: SeatType.EMPTY },
  { col: 2, row: 3, type: SeatType.EMPTY },
  { col: 2, row: 4, type: SeatType.SEAT },
  { col: 3, row: 1, type: SeatType.SEAT },
  { col: 3, row: 2, type: SeatType.EMPTY },
  { col: 3, row: 3, type: SeatType.EMPTY },
  { col: 3, row: 4, type: SeatType.SEAT },
  { col: 4, row: 1, type: SeatType.EMPTY },
  { col: 4, row: 2, type: SeatType.EMPTY },
  { col: 4, row: 3, type: SeatType.EMPTY },
  { col: 4, row: 4, type: SeatType.SEAT },
]
const seatsSchemaOutputFull3: ISeatSchemaOutput = [
  { col: 1, row: 1, type: SeatType.EMPTY },
  { col: 1, row: 2, type: SeatType.EMPTY },
  { col: 1, row: 3, type: SeatType.SEAT },
  { col: 1, row: 4, type: SeatType.EMPTY },
  { col: 1, row: 5, type: SeatType.SEAT },
  { col: 1, row: 6, type: SeatType.EMPTY },
  { col: 1, row: 7, type: SeatType.EMPTY },
  { col: 1, row: 8, type: SeatType.EMPTY },
  { col: 1, row: 9, type: SeatType.SEAT },
  { col: 2, row: 1, type: SeatType.EMPTY },
  { col: 2, row: 2, type: SeatType.SEAT },
  { col: 2, row: 3, type: SeatType.EMPTY },
  { col: 2, row: 4, type: SeatType.EMPTY },
  { col: 2, row: 5, type: SeatType.SEAT },
  { col: 2, row: 6, type: SeatType.SEAT },
  { col: 2, row: 7, type: SeatType.EMPTY },
  { col: 2, row: 8, type: SeatType.EMPTY },
  { col: 2, row: 9, type: SeatType.SEAT },
  { col: 3, row: 1, type: SeatType.SEAT },
  { col: 3, row: 2, type: SeatType.EMPTY },
  { col: 3, row: 3, type: SeatType.EMPTY },
  { col: 3, row: 4, type: SeatType.EMPTY },
  { col: 3, row: 5, type: SeatType.EMPTY },
  { col: 3, row: 6, type: SeatType.EMPTY },
  { col: 3, row: 7, type: SeatType.EMPTY },
  { col: 3, row: 8, type: SeatType.EMPTY },
  { col: 3, row: 9, type: SeatType.EMPTY },
  { col: 4, row: 1, type: SeatType.EMPTY },
  { col: 4, row: 2, type: SeatType.SEAT },
  { col: 4, row: 3, type: SeatType.EMPTY },
  { col: 4, row: 4, type: SeatType.EMPTY },
  { col: 4, row: 5, type: SeatType.EMPTY },
  { col: 4, row: 6, type: SeatType.EMPTY },
  { col: 4, row: 7, type: SeatType.EMPTY },
  { col: 4, row: 8, type: SeatType.EMPTY },
  { col: 4, row: 9, type: SeatType.EMPTY },
  { col: 5, row: 1, type: SeatType.SEAT },
  { col: 5, row: 2, type: SeatType.EMPTY },
  { col: 5, row: 3, type: SeatType.EMPTY },
  { col: 5, row: 4, type: SeatType.EMPTY },
  { col: 5, row: 5, type: SeatType.EMPTY },
  { col: 5, row: 6, type: SeatType.EMPTY },
  { col: 5, row: 7, type: SeatType.EMPTY },
  { col: 5, row: 8, type: SeatType.EMPTY },
  { col: 5, row: 9, type: SeatType.SEAT },
  { col: 6, row: 1, type: SeatType.SEAT },
  { col: 6, row: 2, type: SeatType.EMPTY },
  { col: 6, row: 3, type: SeatType.SEAT },
  { col: 6, row: 4, type: SeatType.EMPTY },
  { col: 6, row: 5, type: SeatType.EMPTY },
  { col: 6, row: 6, type: SeatType.SEAT },
  { col: 6, row: 7, type: SeatType.EMPTY },
  { col: 6, row: 8, type: SeatType.EMPTY },
  { col: 6, row: 9, type: SeatType.SEAT },
]

/**
 * Booking schemas
 */

const bookingSchema1 = [
  { row: 1, col: 1, isBooked: false },
  { row: 1, col: 2, isBooked: false },
  { row: 2, col: 1, isBooked: false },
  { row: 2, col: 2, isBooked: false },
  { row: 3, col: 1, isBooked: false },
  { row: 3, col: 2, isBooked: false },
]
const bookingSchema2 = [
  { row: 1, col: 1, isBooked: false },
  { row: 1, col: 2, isBooked: false },
  { row: 2, col: 1, isBooked: false },
  { row: 3, col: 1, isBooked: false },
  { row: 3, col: 2, isBooked: false },
  { row: 3, col: 3, isBooked: false },
]
const bookingSchema3 = [
  { row: 1, col: 1, isBooked: false },
  { row: 1, col: 2, isBooked: false },
  { row: 1, col: 3, isBooked: false },
  { row: 2, col: 1, isBooked: false },
  { row: 2, col: 2, isBooked: false },
  { row: 3, col: 1, isBooked: false },
  { row: 3, col: 2, isBooked: false },
  { row: 4, col: 1, isBooked: false },
  { row: 4, col: 2, isBooked: false },
  { row: 5, col: 1, isBooked: false },
  { row: 5, col: 2, isBooked: false },
  { row: 6, col: 1, isBooked: false },
  { row: 6, col: 2, isBooked: false },
  { row: 6, col: 3, isBooked: false },
  { row: 6, col: 4, isBooked: false },
]

/**
 * Full cinema schemas
 */

const fullCinemaSchema1 = [
  { col: 1, row: 1, type: SeatType.EMPTY },
  {
    col: 2,
    row: 1,
    type: SeatType.SEAT,
    bookingCol: 1,
    bookingRow: 1,
    isBooked: false,
  },
  {
    col: 3,
    row: 1,
    type: SeatType.SEAT,
    bookingCol: 2,
    bookingRow: 1,
    isBooked: false,
  },
  { col: 4, row: 1, type: SeatType.EMPTY },
  {
    col: 1,
    row: 2,
    type: SeatType.SEAT,
    bookingCol: 1,
    bookingRow: 2,
    isBooked: false,
  },
  { col: 2, row: 2, type: SeatType.EMPTY },
  { col: 3, row: 2, type: SeatType.EMPTY },
  {
    col: 4,
    row: 2,
    type: SeatType.SEAT,
    bookingCol: 2,
    bookingRow: 2,
    isBooked: false,
  },
  { col: 1, row: 3, type: SeatType.EMPTY },
  {
    col: 2,
    row: 3,
    type: SeatType.SEAT,
    bookingCol: 1,
    bookingRow: 3,
    isBooked: false,
  },
  {
    col: 3,
    row: 3,
    type: SeatType.SEAT,
    bookingCol: 2,
    bookingRow: 3,
    isBooked: false,
  },
  { col: 4, row: 3, type: SeatType.EMPTY },
]
const fullCinemaSchema2 = [
  { col: 1, row: 1, type: SeatType.EMPTY },
  {
    col: 2,
    row: 1,
    type: SeatType.SEAT,
    bookingCol: 1,
    bookingRow: 1,
    isBooked: false,
  },
  {
    col: 3,
    row: 1,
    type: SeatType.SEAT,
    bookingCol: 2,
    bookingRow: 1,
    isBooked: false,
  },
  { col: 4, row: 1, type: SeatType.EMPTY },
  { col: 1, row: 2, type: SeatType.EMPTY },
  { col: 2, row: 2, type: SeatType.EMPTY },
  { col: 3, row: 2, type: SeatType.EMPTY },
  { col: 4, row: 2, type: SeatType.EMPTY },
  {
    col: 1,
    row: 3,
    type: SeatType.SEAT,
    bookingCol: 1,
    bookingRow: 2,
    isBooked: false,
  },
  { col: 2, row: 3, type: SeatType.EMPTY },
  { col: 3, row: 3, type: SeatType.EMPTY },
  { col: 4, row: 3, type: SeatType.EMPTY },
  { col: 1, row: 4, type: SeatType.EMPTY },
  {
    col: 2,
    row: 4,
    type: SeatType.SEAT,
    bookingCol: 1,
    bookingRow: 3,
    isBooked: false,
  },
  {
    col: 3,
    row: 4,
    type: SeatType.SEAT,
    bookingCol: 2,
    bookingRow: 3,
    isBooked: false,
  },
  {
    col: 4,
    row: 4,
    type: SeatType.SEAT,
    bookingCol: 3,
    bookingRow: 3,
    isBooked: false,
  },
]
const fullCinemaSchema3 = [
  { col: 1, row: 1, type: SeatType.EMPTY },
  { col: 2, row: 1, type: SeatType.EMPTY },
  {
    col: 3,
    row: 1,
    type: SeatType.SEAT,
    bookingCol: 1,
    bookingRow: 1,
    isBooked: false,
  },
  { col: 4, row: 1, type: SeatType.EMPTY },
  {
    col: 5,
    row: 1,
    type: SeatType.SEAT,
    bookingCol: 2,
    bookingRow: 1,
    isBooked: false,
  },
  {
    col: 6,
    row: 1,
    type: SeatType.SEAT,
    bookingCol: 3,
    bookingRow: 1,
    isBooked: false,
  },
  { col: 1, row: 2, type: SeatType.EMPTY },
  {
    col: 2,
    row: 2,
    type: SeatType.SEAT,
    bookingCol: 1,
    bookingRow: 2,
    isBooked: false,
  },
  { col: 3, row: 2, type: SeatType.EMPTY },
  {
    col: 4,
    row: 2,
    type: SeatType.SEAT,
    bookingCol: 2,
    bookingRow: 2,
    isBooked: false,
  },
  { col: 5, row: 2, type: SeatType.EMPTY },
  { col: 6, row: 2, type: SeatType.EMPTY },
  {
    col: 1,
    row: 3,
    type: SeatType.SEAT,
    bookingCol: 1,
    bookingRow: 3,
    isBooked: false,
  },
  { col: 2, row: 3, type: SeatType.EMPTY },
  { col: 3, row: 3, type: SeatType.EMPTY },
  { col: 4, row: 3, type: SeatType.EMPTY },
  { col: 5, row: 3, type: SeatType.EMPTY },
  {
    col: 6,
    row: 3,
    type: SeatType.SEAT,
    bookingCol: 2,
    bookingRow: 3,
    isBooked: false,
  },
  { col: 1, row: 4, type: SeatType.EMPTY },
  { col: 2, row: 4, type: SeatType.EMPTY },
  { col: 3, row: 4, type: SeatType.EMPTY },
  { col: 4, row: 4, type: SeatType.EMPTY },
  { col: 5, row: 4, type: SeatType.EMPTY },
  { col: 6, row: 4, type: SeatType.EMPTY },
  {
    col: 1,
    row: 5,
    type: SeatType.SEAT,
    bookingCol: 1,
    bookingRow: 4,
    isBooked: false,
  },
  {
    col: 2,
    row: 5,
    type: SeatType.SEAT,
    bookingCol: 2,
    bookingRow: 4,
    isBooked: false,
  },
  { col: 3, row: 5, type: SeatType.EMPTY },
  { col: 4, row: 5, type: SeatType.EMPTY },
  { col: 5, row: 5, type: SeatType.EMPTY },
  { col: 6, row: 5, type: SeatType.EMPTY },
  { col: 1, row: 6, type: SeatType.EMPTY },
  {
    col: 2,
    row: 6,
    type: SeatType.SEAT,
    bookingCol: 1,
    bookingRow: 5,
    isBooked: false,
  },
  { col: 3, row: 6, type: SeatType.EMPTY },
  { col: 4, row: 6, type: SeatType.EMPTY },
  { col: 5, row: 6, type: SeatType.EMPTY },
  {
    col: 6,
    row: 6,
    type: SeatType.SEAT,
    bookingCol: 2,
    bookingRow: 5,
    isBooked: false,
  },
  { col: 1, row: 7, type: SeatType.EMPTY },
  { col: 2, row: 7, type: SeatType.EMPTY },
  { col: 3, row: 7, type: SeatType.EMPTY },
  { col: 4, row: 7, type: SeatType.EMPTY },
  { col: 5, row: 7, type: SeatType.EMPTY },
  { col: 6, row: 7, type: SeatType.EMPTY },
  { col: 1, row: 8, type: SeatType.EMPTY },
  { col: 2, row: 8, type: SeatType.EMPTY },
  { col: 3, row: 8, type: SeatType.EMPTY },
  { col: 4, row: 8, type: SeatType.EMPTY },
  { col: 5, row: 8, type: SeatType.EMPTY },
  { col: 6, row: 8, type: SeatType.EMPTY },
  {
    col: 1,
    row: 9,
    type: SeatType.SEAT,
    bookingCol: 1,
    bookingRow: 6,
    isBooked: false,
  },
  {
    col: 2,
    row: 9,
    type: SeatType.SEAT,
    bookingCol: 2,
    bookingRow: 6,
    isBooked: false,
  },
  { col: 3, row: 9, type: SeatType.EMPTY },
  { col: 4, row: 9, type: SeatType.EMPTY },
  {
    col: 5,
    row: 9,
    type: SeatType.SEAT,
    bookingCol: 3,
    bookingRow: 6,
    isBooked: false,
  },
  {
    col: 6,
    row: 9,
    type: SeatType.SEAT,
    bookingCol: 4,
    bookingRow: 6,
    isBooked: false,
  },
]

export {
  seatsSchemaInput1,
  seatsSchemaInput2,
  seatsSchemaInput3,
  seatsSchemaOutput1,
  seatsSchemaOutput2,
  seatsSchemaOutput3,
  seatsSchemaOutputFull1,
  seatsSchemaOutputFull2,
  seatsSchemaOutputFull3,
  bookingSchema1,
  bookingSchema2,
  bookingSchema3,
  fullCinemaSchema1,
  fullCinemaSchema2,
  fullCinemaSchema3,
}
